<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function gsb_program_finder_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return "plugins/$plugin_type";
  }
}

function gsb_program_finder_theme($existing, $type , $theme, $path) {

  return array(
    'program_isotope_item' => array(
      'template' => 'templates/program-isotope-item',
      'file' => 'theme.inc',
    ),
  );
}
/**
 * Implements hook_menu().
 */
function gsb_program_finder_menu() {
  $items = array();
  $items['admin/config/gsb/program-finder'] = array(
    'title' => 'Program Finder',
    'description' => 'Config Program Finder Image CTAs',
    'access arguments' => array('administer program finder image ctas'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_program_finder_config_main_image_ctas'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'gsb_program_finder.admin.inc',
  );
  $items['admin/config/gsb/program-finder/main'] = array(
    'title' => 'Main Program Finder',
    'access arguments' => array('administer program finder image ctas'),
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'gsb_program_finder.admin.inc',
  );
  $items['admin/config/gsb/program-finder/ee'] = array(
    'title' => 'Exec Education Program Finder',
    'description' => 'Config Exec Education Image CTAs',
    'access arguments' => array('administer program finder image ctas'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_program_finder_config_ee_image_ctas'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'gsb_program_finder.admin.inc',
  );
  $items['program-search/%'] = array(
    'title' => 'Search',
    'page callback' => 'gsb_program_finder_search',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function gsb_program_finder_permission() {
  return array(
    'administer program finder image ctas' =>  array(
      'title' => t('Administer Program Finder Image CTAs'),
      'description' => t('Configure Program Finder Image CTAs settings.'),
    ),
  );
}

function gsb_program_finder_search($search = '') {
  $terms = explode(' ', $search);

  $select = db_select('field_data_field_search_field', 'sf');
  // Select these specific fields for the output.
  $select->addField('sf', 'entity_id');

  $select->condition('sf.bundle', 'program_instance');

  foreach ($terms as $key => $term) {
    $select->condition('sf.field_search_field_value', '% ' . $term . ' %', 'LIKE');
  }
  $entries = $select->execute()->fetchAll(PDO::FETCH_ASSOC);
  $output = array();
  foreach ($entries as $entry) {
    $output[] = $entry['entity_id'];
  }
  drupal_json_output($output);
  drupal_exit();
}
